language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm
  - npm install -g bower
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test -- --single-run
env:
  global:
    secure: rEZNbz5vgPULDHNkz0ISnOOojmxeCgDPCr7wxlpneofChSVYXnhWwAu5zcLCAWozeLey5w7U8MG77liVy7RBrf/BYC6sjz4LqcqV72nRRoNOExGXwpDLNODxNLL/vBFbQiijgfq3PdkTMfBHWJ4NIlYUwSAmU/MTroaWrRd1lFw=
